### ISSUE TITLE
Test payment failed.

### ISSUE THREAD

**Issue by rjohnson914** [saycomputer/retriever-tickets-issues#10]
## Current Behavior
Payment failed
Merchant Setting Requires RecordNo and Frequency.

## Steps to Reproduce

1. Select a movie
2. Select any number of tickets
3. Select the seats
4. Enter test card information and click submit information
5. Payment will fail with the message above.

**Comment by austinkregel** [comment]
I'll take a look at this as soon as possible. :smile:

**Comment by daspecster** [comment]
@rjohnson914 we've had this before and we can't remember what it was. It's something with the test account of mercury.

We just confirmed our test credentials and they are the same as before as far as we can tell.

I wonder if MercuryPay changed something over the weekend?

**Comment by daspecster** [comment]
Update from MercuryPay!

```
I made a change to that this morning actually I will change it back I didn’t not know it was still being used it will work for you in 15 minutes. Sorry for the issue.
 
Thanks,
 
Paul Stewart
MercuryPay
```

**Comment by daspecster** [comment]
This seems to work now but there was a weird blank popup that I had to clear before the confirmation step.

**Comment by daspecster** [comment]
Closing this in favor of #22.
