### ISSUE TITLE
Add zoom stepping for seat map

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [saycomputer/retriever-tickets-issues#101]
Tom mentioned 'stepping' in the OL docs

**Comment by daspecster** [comment]
`zoomFactor` might be the route to achieve this.

See: http://openlayers.org/en/latest/apidoc/ol.View.html

**Comment by ThamanVelasquezBice** [comment]
zoomFactor unfortunately does not work, it gives an error that we can not inverse the matrix

**Comment by ThamanVelasquezBice** [comment]
zoomFactor is not feasible presently due to this error: https://openlayers.org/en/latest/doc/errors/#32
