### ISSUE TITLE
Fix timestamp format for `orderinfo` table.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#107]
The 'timestamp' in 'orderinfo' table does not match the date/time in transmain.
It should be pretty close.
Example on order 1055040053 the date/time is July 31 at 1:37 pm, but the 'timestamp' in 'orderinfo' is July 31 at 7:31 pm

**Comment by austinkregel** [comment]
I don't know how this can be done... It's more date/time timezone manipulations....

**Comment by daspecster** [comment]
Why can't the same code that makes the timestamp for `transmain` just be used for `orderinfo`?

**Comment by austinkregel** [comment]
We are using the same code. They both use `CURRENT_TIMESTAMP` in the database query....

**Comment by daspecster** [comment]
![image](https://user-images.githubusercontent.com/192456/28891726-7c9267d0-7799-11e7-8654-7421cfc763f8.png)
