### ISSUE TITLE
Seatmap does not show up, produces thousands of errors

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [saycomputer/retriever-tickets-issues#110]
25
Cannot fit empty extent provided as geometry.

![wut](https://user-images.githubusercontent.com/18662178/28848576-79778f3e-76e1-11e7-980d-5829993d3f5f.png)

**Comment by ThamanVelasquezBice** [comment]
So this happens whenever getSeatMap fails

**Comment by daspecster** [comment]
@ThamanVelasquezBice can we resolve this by passing an empty object to OpenLayers if the seatmap response is empty?

**Comment by ThamanVelasquezBice** [comment]
An empty object is what causes the error
