### ISSUE TITLE
Check all auditorium configurations on mobile(Android, iPhone)/desktop

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#113]
There is a wide range of auditorium sizes in these movies. Let's make sure they load at the proper size in each case.

- [x] The Belko Experiment
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] John Wick: Chapter 2
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] The Shack
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] Kong: Skull Island
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] Get Out
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] The Lego Batman Movie
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] Before I Fall
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] Teenage Mutant Ninja Turtles: Out of The Shadows
    - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] Logan
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop
- [x] Kong: Skull Island
     - [x] iPhone 6
     - [x] iPhone 5S
     - [x] Android
     - [x] Desktop

**Comment by ThamanVelasquezBice** [comment]
In general the maps seem to be fitting well
