### ISSUE TITLE
Page Replication

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [saycomputer/retriever-tickets-issues#117]
The page reproduces itself on the top of the plugin
## Screenshots (if you have them)

![woah](https://user-images.githubusercontent.com/18662178/28981184-c4ecaafa-791e-11e7-9e0e-20b1597470bc.png)

## Steps to Reproduce

1. Select Movie
2. Select Tickets
3. If seat map doesn't load and the loading... button becomes selectable, click cancel and immediately click loading...

**Comment by daspecster** [comment]
@ThamanVelasquezBice I don't think this is reproducible now that #119 has been merged?

**Comment by ThamanVelasquezBice** [comment]
I was unable to reproduce, so yes
