### ISSUE TITLE
Seat map in the confirmation email.

### ISSUE THREAD

**Issue by austinkregel** [saycomputer/retriever-tickets-issues#12]
I'd really like to see a copy of the seat map in the confirmation email so whom ever ordered the ticket can see where their seat is.
## Desired Behavior

A JPEG or something should be attached in the email.

**Comment by PatrickRetriever** [comment]
While on the receipt email - what is the View Order Button supposed to do? It currently takes the user to the Retriever Gateway API (https://beta-test.retrieverapi.com).

**Comment by austinkregel** [comment]
Currently it doesn't do anything, it's suppose to take the user to view their order in more detail. This hasn't been added yet.

**Comment by PatrickRetriever** [comment]
OK. I didn't want to create a new issue since the return email seems to still be in development.

**Comment by ThamanVelasquezBice** [comment]
At this point it does not seem like this will be a possibility, but once we have time we will look back into this.
