### ISSUE TITLE
Handle expiration date fields better.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#125]
A common complaint when filling out the checkout step was that the expiration field for the credit card was not easy to fill out on phones.

Specifically the forward slash wasn't a button they were expecting to push and it did seem to be a big pump in the process.

We should add  either two fields one for month and one for year or have the field auto-format as they type.

**Comment by ThamanVelasquezBice** [comment]
Closed with https://github.com/saycomputer/retriever-tickets-js/pull/361
