### ISSUE TITLE
Unnoticed indication of action after clicking `Purchase`

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#126]
If the response from Mercury Pay is slow, then it's hard for the user to tell that an action is being performed.

We should ensure that the loading symbol is displayed on mobile after clicking purchase.

**Comment by austinkregel** [comment]
So it looks like Thaman added the spinner about 11 days ago in https://github.com/saycomputer/retriever-tickets-js/pull/329. Is this issue about adding text for what we're doing in the background, like a subcaption for the spinner? So there would be the spinner and then something like `"Sending your information to our credit card processor"` or `"Processing your order"`?

**Comment by daspecster** [comment]
Can't reproduce.
