### ISSUE TITLE
Text the people who order online x minutes before the movie starts

### ISSUE THREAD

**Issue by austinkregel** [saycomputer/retriever-tickets-issues#13]
Ideally, I'd like to see the api run a cron job or something every couple of minutes to text everyone who is going to see a movie X minutes before any given movie they're going to see. This would probably have to be a cron job on the venue machine because having the API server check against 100+ databases in the span of a few minutes is a little much..

**Comment by ThamanVelasquezBice** [comment]
Texting is a feature that we currently cannot tackle due to the lack of a queue system and sms provider. We will reopen this issue if it becomes more possible in the future.
