### ISSUE TITLE
Create new options for sold out button

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [saycomputer/retriever-tickets-issues#137]

**Comment by austinkregel** [comment]
https://codepen.io/austinkregel/full/vJeJMw

**Comment by daspecster** [comment]
https://codepen.io/daspecster/pen/XaeeZo

<img width="188" alt="screen shot 2017-08-14 at 10 26 44 am" src="https://user-images.githubusercontent.com/192456/29276026-3e7525d2-80db-11e7-8dc5-1bd3b1ec7fd2.png">
