### ISSUE TITLE
Text or email receipts 

### ISSUE THREAD

**Issue by austinkregel** [saycomputer/retriever-tickets-issues#14]
If you have ever been a customer of any company that uses Square then you'll be familiar with what I would love to see. It's basically sharing a database of general customer information, with the server being the only thing that has access to the information. This way our customers customers (anyone using the api to buy tickets) would be able to save a few minutes by taping their prefered method of receiving a receipt.

**Comment by ThamanVelasquezBice** [comment]
Would it be possible to text a barcode?

**Comment by ThamanVelasquezBice** [comment]
Texting is a feature that we currently cannot tackle due to the lack of a queue system and sms provider. We will reopen this issue if it becomes more possible in the future.
