### ISSUE TITLE
Repeated session expires message

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#15]
After the session expires and you return to the movie schedule page, when you click a time, you get the session expired message again and immediately.

## Expected Behavior
I should be able to select a new movie time and continue.

## Current Behavior
Session expired modal appears when clicking all desired times.

## Steps to Reproduce

1. Select a movie time.
2. Wait for session to expire (6 minute timeout)
3. Once you are brought back to the movie schedule page, attempt to click another movie time.
4. The session expired time will popup and you will not be able to continue to selecting your ticket types.

**Comment by ThamanVelasquezBice** [comment]
The session is still consistently expired, and after getting that message a few times it still asked me to extend the session. Which also did not extend the session

**Comment by ThamanVelasquezBice** [comment]
Actually it looks like it was an IDE issue of some sort. Code did not update when I pulled the changes. fixed
