### ISSUE TITLE
Seat map not showing up on 10" Samsung Note screen

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#16]
Seat map does not show on my Samsung Note 4 (10" screen). Yes this is an older Note, but it should be backwards compatible with Android... right?

> I could not select seats on my Samsung Note S5 for "Belko Experiment".

Reported by: @PatrickRetriever

## Steps to Reproduce

1.

**Comment by daspecster** [comment]
Looks like we need a device...

**Comment by PatrickRetriever** [comment]
I have noticed, and Alan found this as well, that the seat map doesn't show up for Kong: Skull Island July 6th at 7:30 p.m. We are both on Windows 7 Desk Tops. Is the auditorium configured correctly in Process for Assigned Seating, or is this a GA?

**Comment by daspecster** [comment]
Possibly fixed by https://github.com/saycomputer/retriever-tickets-js/pull/147.

@PatrickRetriever can you guys try it again in a few minutes? It takes like 5 minutes for it to release. Make sure you hard refresh too.

**Comment by austinkregel** [comment]
We did test the plugin on a 10" Smartab, and the plugin worked. If this issues happens again, please let us know!
