### ISSUE TITLE
Session Expired Screen needs to include instructions on how to "Refresh".

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#18]
Session Expired Screen needs to include instructions on how to "Refresh".

Reported by: @PatrickRetriever

**Comment by austinkregel** [comment]
Can @PatrickRetriever give any more information about why this was needed? What did you encounter for you to have to refresh the page?

**Comment by PatrickRetriever** [comment]
On my Windows 7 desktop, a message box pops up that says Session Expired. I closed the message box and was not able to do anything else until I refreshed the screen.

**Comment by austinkregel** [comment]
Did the message box keep reappearing when you clicked a new show time?

**Comment by PatrickRetriever** [comment]
Hey Austin, 

So, the other issue here is that the session is expiring, but not the seat selections. So, if after a session expires, I go in and order a new seat, I am now purchasing two seats. So in reality, the session has not expired. That could be why Alan and I purchased 8 seats yesterday, but we're charged for 10.

**Comment by austinkregel** [comment]
@PatrickRetriever the goods news is that I just pushed a fix for that a few minutes ago :) (for dev team reference https://github.com/saycomputer/retriever-tickets-js/pull/149)
