### ISSUE TITLE
Movie synopsis can be shorter or even click to see

### ISSUE THREAD

**Issue by rjohnson914** [saycomputer/retriever-tickets-issues#19]
## Expected Behavior
Synopsis shouldn't take up so much real estate.

## Steps to Reproduce

1.

**Comment by austinkregel** [comment]
Movie synopses are actually controlled by a database on the API server called `filmdb` we don't type in or control the length of the synopsis.

**Comment by rjohnson914** [comment]
That should work, just one or two lines and "show more".

**Comment by austinkregel** [comment]
This was patched in an earlier PR :) (for dev team reference https://github.com/saycomputer/retriever-tickets-js/pull/183)
