### ISSUE TITLE
Set email confirmation text to black.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#191]
See: https://github.com/saycomputer/retriever-ticketing-api/pull/268

All text should be black, but currently the center text is grey and doesn't print will.

**Comment by austinkregel** [comment]
![img_20170822_122219](https://user-images.githubusercontent.com/5355937/29576111-adac5c86-8734-11e7-88dc-6b327e101d02.jpg)

**Comment by ThamanVelasquezBice** [comment]
This appears to have been an issue with @saymikecross's printer, it printed just fine for @austinkregel
