### ISSUE TITLE
Possibly a weird state issue?

### ISSUE THREAD

**Issue by austinkregel** [saycomputer/retriever-tickets-issues#20]
_This issue is on behalf of a good friend of mine who I asked to break the site. If this issue cannot be replicated please close it._ :smile: 

I did six adults, six kids, and then two for the other three categories. I hit next, took me to seating. I hit next again, and the screen locked up. The buttons disappeared and it only allows you to move around the screen. I went back, changed the number of tickets to just six adults and nothing else, went forward again, and still no buttons or anything. 

## Expected Behavior

I should be able to select the tickets I want and then there should be validation on the seatmap (if there isn't already) to prevent anyone from moving forward. The buttons should always remain on screen.

## Screenshots (if you have them)
![image](https://user-images.githubusercontent.com/5355937/27886192-f9ff4528-61a8-11e7-9a79-deb4c821f242.png)
![image](https://user-images.githubusercontent.com/5355937/27886315-87282a1e-61a9-11e7-8933-564d1e0d524a.png)

## Steps to Reproduce

1. Select 6 adults, 6 kids, and then 2 of every other type of ticket
2. Hit next
3. Hit next again and don't select any seats.
4. Hit back.
5. Change the seats to some other number.
6. Hit next.

**Comment by daspecster** [comment]
@austinkregel if you think this is user error, then let's close it for now.
