### ISSUE TITLE
Set expires and caching headers in all server responses.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#202]
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

**Comment by austinkregel** [comment]
Soo this is a non issue... Or so it seems.

**Comment by daspecster** [comment]
Nope, still issue. Browsers/apps need to know when they should get new content.

**Comment by austinkregel** [comment]
So how do?

**Comment by daspecster** [comment]
Do you not do?

**Comment by daspecster** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

**Comment by austinkregel** [comment]
I added `expires modified 10m;` for the api, beta-plugin, and plugin.
