### ISSUE TITLE
Don't build plugin directly on server.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#208]
`plugin.retrievercinemas.com` should not have node or anything installed on it. It should just serve static files.

**Comment by austinkregel** [comment]
I don't see the issue here. Please explain.

**Comment by daspecster** [comment]
Sure! It's not just security it's also a deployment thing.

There are advantages to running a slim version of linux without any outside dependencies.
- Adding packages increases your risk for security vulnerabilities.
- Adding packages adds points that could cause version conflicts(e.g. node v7.1 was used for development but v7.1.1 was released and has a syntax issue or incompatibility and thus blocks release).
- Deploying to multiple servers means you would have to compile on each instance which is inefficient.

There are more reasons you can read about I'm sure.

**Comment by austinkregel** [comment]
I honestly don't think this is an issue we can address at the moment. When we change the production environment to a new server I believe this will be more relevant. Closing for now.
