### ISSUE TITLE
Add caching back to getSchedule

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#210]
For scaling and good internet stewardship, we should be utilizing caching for routes that it will work for.

# Caching strategies

## Cache Expires

The simplest caching strategy is to set an expires value to
pull new data after a set amount of time. The down side is
that a venue will have to know how long the expiration is
and plan accordingly.

e.g. Cache expires after 30 minutes, if a venue wants a new showing
to be displayed at 10:30pm, then they would need to add it/alter it
by 10pm.

## Cache Reset API Endpoint

Currently there is an API endpoint to release the cache for a venue
location. The best way to utilize this would be to call this endpoint
whenever the showtime/schedule is altered through the VENU PROCESS.

## Remove Cache

We could remove the cache but this will make the initial loading of
the schedule much slower. Right now we're seeing load times of under
200ms now it's about ~3 seconds.

**Comment by austinkregel** [comment]
Add caching back? Didn't we just agree to remove the cache for now?
