### ISSUE TITLE
Modal buttons are wrong

### ISSUE THREAD

**Issue by austinkregel** [saycomputer/retriever-tickets-issues#227]
1. Open starmount
2. Choose movie && time.
3. Select no tickets
4. Checkout.

![image uploaded from ios](https://user-images.githubusercontent.com/5355937/29972598-a239ad18-8efa-11e7-91de-ba9e8acf88ff.jpg)

**Comment by ThamanVelasquezBice** [comment]
This was fixed yesterday, just needs to be released. @austinkregel
