### ISSUE TITLE
Respect `ticketsales`, `xmlinternet`, `trashcan` statuses.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#228]
<img width="961" alt="screen shot 2017-09-01 at 12 30 03 pm" src="https://user-images.githubusercontent.com/192456/29978921-50cbbef0-8f11-11e7-8eb8-92d32404eaab.png">

**Comment by austinkregel** [comment]
I believe we already do this as of https://github.com/saycomputer/retriever-ticketing-api/pull/318

**Comment by ThamanVelasquezBice** [comment]
@austinkregel if you are sure then I'd say close the issue, it can be reopened if needed
