### ISSUE TITLE
Cancel instead of Back?

### ISSUE THREAD

**Issue by rjohnson914** [saycomputer/retriever-tickets-issues#29]
## Expected Behavior
Cancel button instead of Back.

## Current Behavior
I think we might want to consider canceling the order and starting over instead of allowing the customer to go back. 
If you select 6 tickets, select the seats and then go back and add 1 it will allow the addition of 1 seat, but you can't be sure which 6 you selected originally. 
However, going back and reducing from 6 to 5 tickets does not remove a selected seat.

**Comment by daspecster** [comment]
That would make our lives easier for the moment I think.

**Comment by austinkregel** [comment]
@daspecster added this behavior in his recent PR he made on last Friday (for dev team reference https://github.com/saycomputer/retriever-tickets-js/pull/170)
