### ISSUE TITLE
Cannot Select Seats

### ISSUE THREAD

**Issue by PatrickRetriever** [saycomputer/retriever-tickets-issues#30]
## Expected Behavior

The Lego Batman July 6 9:15 p.m.
Selected 2 Adults, 2 Children, 2 Military, 2 Senior Tickets
I have recreated this issue a couple of times....

Should be able to select eight seats.

## Current Behavior

Went to seat map and clicked on eight seats. None of the selected seats locked. Clicked next and the system told me that I needed to select my seats. Clicked my seats again. A message pops up that says all of my seats have been selected. 
## Screenshots (if you have them)
![select](https://user-images.githubusercontent.com/29931131/27934867-152fd8a0-6265-11e7-847f-4cad21ea4747.JPG)
![selected](https://user-images.githubusercontent.com/29931131/27934871-179efc6a-6265-11e7-9d15-acd9e1b3b889.JPG)

## Steps to Reproduce

1. Selected 8 tickets (2 of each to 6:15 p.m.) Lego Batman
2. Hit Next
3. Clicked on seats but there was no indicator of the seats being selected until the system message came up and said all seats had been selected.
4. Hit Next.
5. The message box pops up and tells me to select seats. 
6. Go back to step three.
7. Tried selecting different seats. 
8. Received message that seats had already been selected.

**Comment by PatrickRetriever** [comment]
Alan had the same issue with the 9:30 p.m showing of John Wick: Part Two

**Comment by austinkregel** [comment]
If this happens again today please let us know! We'll be testing/bug-fixing all day, and we'll try to replicate this issue :)

**Comment by ThamanVelasquezBice** [comment]
It may be that someone else locked those seats while you were on the seat selector, the API will not allow you to lock or unlock a seat that was not created in your order
