### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by rjohnson914** [saycomputer/retriever-tickets-issues#31]
## Expected Behavior
A shopping cart on the page as I purchase. The fee only shows at checkout.

## Steps to Reproduce

1.

**Comment by austinkregel** [comment]
Can you provide screenshots?

**Comment by rjohnson914** [comment]
Here's one. 

![shopping_cart](https://user-images.githubusercontent.com/4020042/27962092-cd6cbcb4-62fe-11e7-92d0-ff15b0cac93f.png)

**Comment by austinkregel** [comment]
I'm not sure I understand what you're looking for... Can you elaborate more?

**Comment by daspecster** [comment]
@rjohnson914 so what we figured out, is that the ticket prices on the right side of the site are just static values left over from the template and should be disregarded.

So as far as I know, there are no extra fees that get added at the end of the checkout. @austinkregel  explained it pretty well [here](https://github.com/saycomputer/retriever-tickets-issues/issues/25#issuecomment-313677478).

**Comment by rjohnson914** [comment]
These are dynamic and populate as you select. Here is Fandango's from Brenden. I can only assume they will expect something similar. We can address this down the road after they review. 

![fandango_secure_checkout](https://user-images.githubusercontent.com/4020042/27962479-087e9876-6300-11e7-9b9d-d58feeab018f.png)

**Comment by austinkregel** [comment]
Based on what I saw with our interactions in the database there is no convenience fee stored in the database. Geraud might have more of an in sight on that than us, but as far as I can tell there is no convenience fee. (I would tag him but I don't know his handle on GitHub.)

**Comment by daspecster** [comment]
I'm wondering if the $1.50 fee is for Fandango but I can't find information on fandango.com about it.

**Comment by austinkregel** [comment]
The convenience fee is charge by Fandango for Fandango's benefit. [A link to Fandango's help center](http://fandango.custhelp.com/app/answers/new_detail/a_id/82)
