### ISSUE TITLE
Showtimes page layout

### ISSUE THREAD

**Issue by rjohnson914** [saycomputer/retriever-tickets-issues#33]
## Expected Behavior
Here is what we have in mind for a layout. "View trailer" should open in a new tab or maybe a popup. 
![showtimes](https://user-images.githubusercontent.com/4020042/28077231-30489d48-662f-11e7-9e25-dc05a675e433.jpg)

## Steps to Reproduce

1.

**Comment by austinkregel** [comment]
Where can we get the trailer URL?

**Comment by rjohnson914** [comment]
Youtube has them, here are a couple.
Link: https://youtu.be/JDcAlo8i2y8
Embed: <iframe width="702" height="395" src="https://www.youtube.com/embed/JDcAlo8i2y8" frameborder="0" allowfullscreen></iframe>

**Comment by austinkregel** [comment]
What I mean is, is there any link stored in the database or a way that you guys get the link programmatically?

**Comment by rjohnson914** [comment]
Ah, sorry. There must be, because we are doing it now. That would be a Geraud question.

**Comment by austinkregel** [comment]
I found out how you guys did it in the old site (for dev team reference [retriever-tickets.php/schedule.php](https://github.com/saycomputer/retriever-tickets.php/blob/7acaddaa7494e71208ff782c050a0ef8443b61b8/schedule.php#L190)

**Comment by austinkregel** [comment]
This has been fixed as of July 11th :) (for dev team reference https://github.com/saycomputer/retriever-tickets-js/pull/183)
