### ISSUE TITLE
Eliminate all page hops.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#34]
When going to a step in the plugin, it should not hop after loading.

**Comment by austinkregel** [comment]
What do you mean "hop"

**Comment by daspecster** [comment]
When a page jumps after some dynamic content on the page finishes loading.

**Comment by austinkregel** [comment]
I believe you fixed this yesterday?

**Comment by daspecster** [comment]
Nope :( those places weren't the issue. Specifically on the ticket type selection page, what happens is the page jumps due to the input selectors finally loading. So I think some CSS would fix it but I'm not sure.
