### ISSUE TITLE
Seat Map Turned Off - Ticket Types don't load on Purchase Tickets Page

### ISSUE THREAD

**Issue by PatrickRetriever** [saycomputer/retriever-tickets-issues#38]
I turned off the seat map for Auditorium 8 (Logan), saved and activated. Tested by trying to purchase an online ticket. Ticket Purchase page would not load the ticket types.

## Expected Behavior

Ticket types should load for selection. 

## Current Behavior

Blue loading circle cycles and nothing happens.

## Screenshots (if you have them)
![auditorium off](https://user-images.githubusercontent.com/29931131/28183394-831ebd24-67cc-11e7-8800-2c4c665a9b5b.PNG)

**Comment by daspecster** [comment]
I noticed this too for some theaters but it resolved after a while. I'm guessing network issues but it's something we should look into more.

**Comment by PatrickRetriever** [comment]
I doubt that it's network related because I can go to a different auditorium and it loads up fine. I have only run into this issue when the assigned seating is turned off at the process level.
