### ISSUE TITLE
Cancel Button is not clearing the seat selections.

### ISSUE THREAD

**Issue by PatrickRetriever** [saycomputer/retriever-tickets-issues#39]
When the user clicks cancel, the user's order remains in the selected inventory.

## Expected Behavior

All selected seats should be immediately released for sale. 

## Current Behavior

Seat selection is remaining even after the order has been cancelled.

**Comment by daspecster** [comment]
@ThamanVelasquezBice wasn't this closed by https://github.com/saycomputer/retriever-tickets-js/pull/216?

**Comment by austinkregel** [comment]
Technically no, that PR only fixed the logic of the button call. Previously it didn't actually cancel any order other than successful orders...

**Comment by austinkregel** [comment]
This will actually be fixed when we fix #46
