### ISSUE TITLE
Overflow seats

### ISSUE THREAD

**Issue by austinkregel** [saycomputer/retriever-tickets-issues#40]
The theater manager will set a low seat count if they don't want to sell out online. With assigned seating, there is very little reason not to sell out online other than pissed off walk-in customers. The current retriever Tickets stops selling tickets at Low Seat Count + 10%, so if the low seat count is 10, Retriever Tickets will stop selling at 11.

I believe that what Ed is saying is that if the theater manager wants to be able to sell out online, they should be able to.
## Expected Behavior

The seats should have "overflow"
## Current Behavior

Seats don't? have overflow?

**Comment by daspecster** [comment]
@rjohnson914 I'm not sure what the priority of this really is. Is this something we _need_ to launch for Brenden?

**Comment by rjohnson914** [comment]
No, I don't believe this is necessary for launch.

**Comment by ThamanVelasquezBice** [comment]
Closed by https://github.com/saycomputer/retriever-ticketing-api/pull/277
