### ISSUE TITLE
Seat Map - Legend Colors

### ISSUE THREAD

**Issue by PatrickRetriever** [saycomputer/retriever-tickets-issues#42]
The current colors are too close together. It is difficult to distinguish between the pending selection and the selected color hues.  

## Expected Behavior

There needs to be a clear and obvious difference between  all colors during the selection process.

**Comment by daspecster** [comment]
I think a good solution would be to make the "locking seat" color a tertiary color. Like yellow perhaps?

**Comment by austinkregel** [comment]
Is this a better color? 
![image](https://user-images.githubusercontent.com/5355937/28372700-604fd0ac-6c6e-11e7-8a4e-88b8c2ad7adf.png)
