### ISSUE TITLE
Order ID doesn't exist when cancelling on checkout

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#46]
## Expected Behavior
You should be able to cancel an order at any point after you select your ticket types and before you view the confirmation page with your receipt.

## Current Behavior
On the `checkout` step, an error is returned about 50% of the time indicating that the order ID couldn't be found. 

Related? https://github.com/saycomputer/retriever-tickets-js/issues/217

**Comment by austinkregel** [comment]
I believe this might be fixed in saycomputer/retriever-ticketing-api#133

**Comment by austinkregel** [comment]
I think this was fixed in #133
