### ISSUE TITLE
Start timer at correct time after phone suspend.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#49]
## Expected Behavior
Timer should continue to count(or calculate the time left) even if the phone suspends and stops counting down.

## Current Behavior
The timer will start right where it left off when the phone was suspended and get out of sync with the true expiration.

**Comment by ThamanVelasquezBice** [comment]
Fixed with https://github.com/saycomputer/retriever-tickets-js/pull/345
