### ISSUE TITLE
Over Charging

### ISSUE THREAD

**Issue by PatrickRetriever** [saycomputer/retriever-tickets-issues#59]
The math calculations are incorrect on the summary page and totals page.
## Expected Behavior

The math should be a correct reflection of the purchase price.
## Screenshots (if you have them)
![price error](https://user-images.githubusercontent.com/29931131/28334111-5523aeea-6bb7-11e7-8f9c-365c1a6f38ac.PNG)

## Steps to Reproduce

1. Select Feature
2. Select Tickets (I've been doing more than 4)
3. Select Seats
4. On next screen, total price is astronomical. 

## Context (Environment)

The customer is being overcharged.

**Comment by austinkregel** [comment]
I'm not able replicate this on retriever cinemas. I followed your steps and I am ending with the correct math

![image](https://user-images.githubusercontent.com/5355937/28334642-bbcf8134-6bc9-11e7-8a72-d6d4d25ac998.png)

**Comment by daspecster** [comment]
@PatrickRetriever we haven't been able to reproduce.

<img width="585" alt="screen shot 2017-07-18 at 2 58 17 pm" src="https://user-images.githubusercontent.com/192456/28334610-a17ad838-6bc9-11e7-9032-365e2f6d2bfd.png">


There was an issue with how we concatenated the prices before. Maybe double check and make sure you clear your cache.

**Comment by PatrickRetriever** [comment]
This does appear to be working now. Thank You,.
