### ISSUE TITLE
Call releaseSeat if Someone Abandons their Order

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [saycomputer/retriever-tickets-issues#6]
## Expected Behavior

The seats from an abandoned order should not stay selected
## Current Behavior

Seats stay selected regardless
## Steps to Reproduce

1. Select a seat and then refresh the page

## Context (Environment)

This will prevent seats from being available for selection

## Detailed Description

I don't have a specific fix that I could think of but there needs to be a way to call releaseSeat on abandoned orders

**Comment by austinkregel** [comment]
This is fixed by saycomputer/retriever-ticket-api#90
