### ISSUE TITLE
Fix fee calculation on checkout page.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#60]
## Expected Behavior
Checkout should show total with fee included.

## Current Behavior
Fee is left out of total

**Comment by geigerjoe** [comment]
This appears not to be fixed.  Convenience fee is charged twice

**Comment by austinkregel** [comment]
Please attach screenshots @geigerjoe

**Comment by geigerjoe** [comment]
![img_1477](https://user-images.githubusercontent.com/30267195/28380539-abd0c1e6-6c85-11e7-8023-c41b45baec21.PNG)
![img_1478](https://user-images.githubusercontent.com/30267195/28380540-abf9200a-6c85-11e7-90e9-8962ab58e71d.PNG)

**Comment by austinkregel** [comment]
Interesting >.> I'll look into this right now

**Comment by austinkregel** [comment]
I just fixed this about 45 seconds ago :smile: please allow 5 minutes before testing this again, also remember to empty your browser cache when trying again :smile:
