### ISSUE TITLE
Clicking back from `Checkout` from a theater without assigned seating, takes you to the assigned seating anyway.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#7]
If you're at the 'checkout' step on a theater that does not have assigned seating and you click `back`, you will be taken to the `select seats` step, but it will be blank.

## Expected Behavior
Should return you to the `ticket type` step.

**Comment by austinkregel** [comment]
Technically "fixed" because we no longer allow you to go back...
