### ISSUE TITLE
Show price table for ticket selection.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#71]
## Expected Behavior
Display detailed information for pricing for a user.

<img width="579" alt="screen shot 2017-07-24 at 12 20 08 pm" src="https://user-images.githubusercontent.com/192456/28533268-79fa84e8-706a-11e7-87b8-4fa092b65d76.png">

## Current Behavior
<img width="503" alt="screen shot 2017-07-24 at 12 20 45 pm" src="https://user-images.githubusercontent.com/192456/28533297-8f27448c-706a-11e7-97e8-8d215908826e.png">

**Comment by austinkregel** [comment]
![image](https://user-images.githubusercontent.com/5355937/28537936-82a147ac-707a-11e7-9028-f5b81fdbf9e3.png)

**Comment by daspecster** [comment]
closed by https://github.com/saycomputer/retriever-tickets-js/pull/286
