### ISSUE TITLE
Make sure that cancel button is spaced away from continue buttons.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#74]
## Expected Behavior
Cancel button should be next to the continue button instead of on top.
There should also be space between them.

## Current Behavior
<img width="345" alt="screen shot 2017-07-24 at 12 55 27 pm" src="https://user-images.githubusercontent.com/192456/28534651-64a424f0-706f-11e7-887d-21bfa1eac312.png">

**Comment by austinkregel** [comment]
Please see issue https://github.com/saycomputer/retriever-tickets-issues/issues/67
