### ISSUE TITLE
Move screen to outside map.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#75]
## Expected Behavior
Screen bar should be outside the map area.

**Comment by austinkregel** [comment]
![image](https://user-images.githubusercontent.com/5355937/28537867-515c362a-707a-11e7-9d9e-b0b852b7bda4.png)

**Comment by daspecster** [comment]
Closed by https://github.com/saycomputer/retriever-tickets-js/pull/280
