### ISSUE TITLE
Figure out available seat color

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#76]
## Expected Behavior
The available seat color should not be grey. We use grey as a disabled color.

**Comment by daspecster** [comment]
I suggest #B0E7C6.

<img width="191" alt="screen shot 2017-07-24 at 2 50 13 pm" src="https://user-images.githubusercontent.com/192456/28539376-6e37c96c-707f-11e7-8164-819839f27ef1.png">

**Comment by ThamanVelasquezBice** [comment]
![screenshot from 2017-07-24 15-01-21](https://user-images.githubusercontent.com/18662178/28539828-0c4efa5c-7081-11e7-97de-b06e237ba85d.png)
