### ISSUE TITLE
Discuss locking the rotation of the plugin

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#79]
## Expected Behavior
We could disable horizontal views of the plugin on mobile.

## Current Behavior
The browser controls the rotation.

**Comment by austinkregel** [comment]
I don't think we should lock the rotation of the plugin. I don't think it's worth it. Our scaling solutions works pretty well with rotation. If anyone else thinks we should lock it I'd love to hear the reasoning :)

**Comment by geigerjoe** [comment]
Rotating from vertical to horizontal while on the seat map creates a pretty bad and difficult to manipulate view in the horizontal orientation.  If this can not be improved, I recommend not being able to rotate only the seat map if that is possible.  Overall, the seat map on my iphone 6 is too tall and seems it could be optimized which I believe is contributing to the poor horizontal view.  Thoughts?
![seat map on iphone 0001](https://user-images.githubusercontent.com/30267195/28782565-8457de4c-75db-11e7-8fdd-7c6b1fb9197a.PNG)
![seat map on iphone 0002](https://user-images.githubusercontent.com/30267195/28782569-85a40816-75db-11e7-9670-2f2b71aaba64.PNG)

**Comment by daspecster** [comment]
https://css-tricks.com/snippets/css/orientation-lock/

**Comment by daspecster** [comment]
This doesn't seem widely supported at this time.
