### ISSUE TITLE
Seat map too large

### ISSUE THREAD

**Issue by rjohnson914** [saycomputer/retriever-tickets-issues#84]
You've probably noticed this, but the seat map for TMNT is too large to fit. And the ticket type sort order is wrong. 

![screenshot 2017-07-25 11 49 31](https://user-images.githubusercontent.com/4020042/28581166-93f82cb8-712f-11e7-849a-5d9c6268dff4.png)

## Steps to Reproduce

1.

**Comment by ThamanVelasquezBice** [comment]
@rjohnson914 do you just mean that they should be alphabetical?

**Comment by rjohnson914** [comment]
Only the reserved auditorium has Child at the top. 

![screenshot 2017-07-25 14 15 56](https://user-images.githubusercontent.com/4020042/28587093-efc5f516-7143-11e7-9cee-2b77f0636f1c.png)

**Comment by austinkregel** [comment]
@rjohnson914 I'm still not understanding what you mean. What's the desired behavior? What are you expecting the sort order to be like? Should it be alphabetical? sorted by price?

**Comment by daspecster** [comment]
@ThamanVelasquezBice I believe this could just be that we need a lower `minZoom` and it might work.

**Comment by rjohnson914** [comment]
Adult should be on top like all the other movies. 

![screenshot 2017-07-25 14 25 41](https://user-images.githubusercontent.com/4020042/28587699-143f9fd0-7146-11e7-9a79-ed51fbb89872.png)
