### ISSUE TITLE
Confirm that seats get released when cancelling from the checkout step.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#85]
## Expected Behavior
Seats should be released if cancelled from the checkout step.

## Current Behavior
> I did see where 2 seats I
selected for Ninja Turtles (2:30 pm 7/24 show) then canceled at the last
payment step still showed reserved when I went back in a 2nd time.
>Thanks,
>Pat

**Comment by ThamanVelasquezBice** [comment]
From what I saw during testing, the seats *do* unlock when canceling an order. I believe the issue arises when the order is not successfully canceled. They should unlock once the order expires
