### ISSUE TITLE
Seat map scale is broken with current design.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#9]
Note: This has been put on hold, since we're currently implementing a new design.

![screen shot 2017-07-05 at 10 44 22 am](https://user-images.githubusercontent.com/192456/27869806-101fd1e0-616f-11e7-9583-4b825e110adb.png)

**Comment by ThamanVelasquezBice** [comment]
How about now sir

**Comment by daspecster** [comment]
I think we need to increase min-zoom?

![img_3452](https://user-images.githubusercontent.com/192456/28072977-739b050c-6622-11e7-95df-083afe6fb863.PNG)

**Comment by ThamanVelasquezBice** [comment]
how about now on your iPhone

**Comment by daspecster** [comment]
Closed by https://github.com/saycomputer/retriever-tickets-js/pull/241
