### ISSUE TITLE
Look into strange situation where fonts are wacky sizes on some Android devices.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#92]
A galaxy S5, with the default browser. (android stock browser) Apparently there is extra padding on some android phones.

Ensure that mobile browsers treat the sizing correctly.

**Comment by austinkregel** [comment]
Do we have any screenshots?

**Comment by daspecster** [comment]
Nope, we need to ask for them.

**Comment by austinkregel** [comment]
I think that this might be to Samsung device's ability to change the default font for their OS.

**Comment by austinkregel** [comment]
I looked into this on an S3, Pixel XL, Nexus 6P, Nexus 5X, Moto X (2014), Droid RAZR MAXX HD, iPhone 5s, iPhone 7+ and an iPhone 5. I have not been able to replicate any extra padding on any of these devices.
