### ISSUE TITLE
Remove toast messages and find an alternate solution.

### ISSUE THREAD

**Issue by daspecster** [saycomputer/retriever-tickets-issues#94]

**Comment by ThamanVelasquezBice** [comment]
I think we should remove toasts from the seatmap all together and change the warning on the Selection page to a modal or something

maybe have the "You have selected all your seats." stuff as a modal too

**Comment by daspecster** [comment]
What if we leave the toasts for now and make changes incrementally?

1. Change warnings/errors to modals.
2. Figure out UI to communicate seat locking pending statuses without toast messages?

**Comment by daspecster** [comment]
See: http://openlayers.org/en/latest/examples/feature-animation.html

**Comment by ThamanVelasquezBice** [comment]
We are like 70% of the way there, gotta make the modals look better and figure somethin out for the success messages
